// <auto-generated />
using System;
using CourseDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseDemo.Data.Migrations
{
    [DbContext(typeof(CourseContext))]
    partial class CourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseDemo.Domain.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClusterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clusters","CareerTech");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BeginSequence")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("CreditAdvancementAvailable")
                        .HasColumnType("bit");

                    b.Property<bool?>("CreditRecoveryAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("CreditTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CreditUnits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndSequence")
                        .HasColumnType("int");

                    b.Property<int?>("HighGradeId")
                        .HasColumnType("int");

                    b.Property<int?>("LowGradeId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLevelId");

                    b.HasIndex("CourseTypeId");

                    b.HasIndex("HighGradeId");

                    b.HasIndex("LowGradeId");

                    b.ToTable("Courses","Common");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.CourseLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseLevelCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourseLevels","Common");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.CourseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourseTypes","Common");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.DeliveryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryTypes","Common");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades","Common");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TraditionalForFemales")
                        .HasColumnType("bit");

                    b.Property<bool?>("TraditionalForMales")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Programs","CareerTech");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.ProgramAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProgramId");

                    b.ToTable("ProgramCourses","CareerTech");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags","Common");
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.Cluster", b =>
                {
                    b.OwnsOne("CourseDemo.Domain.Models.ValidPeriod", "ValidPeriod", b1 =>
                        {
                            b1.Property<int>("ClusterId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("BeginYear")
                                .HasColumnName("BeginYear")
                                .HasColumnType("int");

                            b1.Property<int?>("EndYear")
                                .HasColumnName("EndYear")
                                .HasColumnType("int");

                            b1.HasKey("ClusterId");

                            b1.ToTable("Clusters");

                            b1.WithOwner()
                                .HasForeignKey("ClusterId");
                        });
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.Course", b =>
                {
                    b.HasOne("CourseDemo.Domain.Models.CourseLevel", "CourseLevel")
                        .WithMany()
                        .HasForeignKey("CourseLevelId");

                    b.HasOne("CourseDemo.Domain.Models.CourseType", "CourseType")
                        .WithMany()
                        .HasForeignKey("CourseTypeId");

                    b.HasOne("CourseDemo.Domain.Models.Grade", "HighGrade")
                        .WithMany()
                        .HasForeignKey("HighGradeId");

                    b.HasOne("CourseDemo.Domain.Models.Grade", "LowGrade")
                        .WithMany()
                        .HasForeignKey("LowGradeId");

                    b.OwnsOne("CourseDemo.Domain.Models.ValidPeriod", "ValidPeriod", b1 =>
                        {
                            b1.Property<int>("CourseId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("BeginYear")
                                .HasColumnName("BeginYear")
                                .HasColumnType("int");

                            b1.Property<int?>("EndYear")
                                .HasColumnName("EndYear")
                                .HasColumnType("int");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.Program", b =>
                {
                    b.OwnsOne("CourseDemo.Domain.Models.ValidPeriod", "ValidPeriod", b1 =>
                        {
                            b1.Property<int>("ProgramId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("BeginYear")
                                .HasColumnName("BeginYear")
                                .HasColumnType("int");

                            b1.Property<int?>("EndYear")
                                .HasColumnName("EndYear")
                                .HasColumnType("int");

                            b1.HasKey("ProgramId");

                            b1.ToTable("Programs");

                            b1.WithOwner()
                                .HasForeignKey("ProgramId");
                        });
                });

            modelBuilder.Entity("CourseDemo.Domain.Models.ProgramAssignment", b =>
                {
                    b.HasOne("CourseDemo.Domain.Models.Course", "Course")
                        .WithMany("ProgramAssignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CourseDemo.Domain.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.OwnsOne("CourseDemo.Domain.Models.ValidPeriod", "ValidPeriod", b1 =>
                        {
                            b1.Property<int>("ProgramAssignmentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("BeginYear")
                                .HasColumnName("BeginYear")
                                .HasColumnType("int");

                            b1.Property<int?>("EndYear")
                                .HasColumnName("EndYear")
                                .HasColumnType("int");

                            b1.HasKey("ProgramAssignmentId");

                            b1.ToTable("ProgramCourses");

                            b1.WithOwner()
                                .HasForeignKey("ProgramAssignmentId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
